import { IHandyRedis } from "handy-redis";

// Generated by https://quicktype.io

// member-queue-start Entrée d'un numéro dans la file 
// bridge-agent-start Prise en charge d'un numéro dans la file
// bridge-agent-fail
// member-queue-end
// bridge-agent-end
// member-count
// agent-offering
export type LineEvent = 'start_ringing' | 'start_calling' | 'end_ringing' | 'end_calling' | 'registered';
export type QueueEvent = 'member-queue-start' | 'bridge-agent-start' | 'bridge-agent-fail' | 'member-queue-end' | 'bridge-agent-end' | 'members-count' | 'agent-offering';
// timestamp in sec as String
type TSSecString = string;

/**
 * v1
 */
export interface VoipEventV1Root {
    Session: string;
    Message: string;
    Events:  VoipEventV1[];
}
/**
 * V1
 */
export interface VoipEventV1 {
    Event:     LineEvent | QueueEvent;
    Token:     string;
    Service:   'queues' | string;
    Ressource: string;
    Timestamp: number;
    Date:      string;
    Data:      IEvData;
    Details:   Details;
}
/**
 * V2
 */
export interface IVoipEventV2 {
    event: LineEvent | QueueEvent;
    token: string;
    service: 'queues' | string;
    ressource: string; // 0033900000000
    timestamp: number;
    date: string;
    data: IEvData;
    details: Details;
}
/**
 * V1 + V2
 */
export interface IEvData {
    Action: LineEvent | QueueEvent;
    Agent: string; // 0033900000000
    Calling: string; // 0033900000000
    Count: string; // '1'|'2'|'3' ...
    Protocol: 'sip' | string;
    Queue: string; // 0033900000000
    QueueAgent: string; // agent_0033900000000_id
    QueueAgentAnsweredTime: TSSecString; // "1559904023"
    QueueAgentCalledTime: TSSecString; // "1559904023"
    QueueAgentSystem: 'single_box' | string;
    QueueAgentUUID: string; // UUID
    QueueCause: 'Terminated' | string;
    QueueHangupCause: 'LOSE_RACE' | 'SUCCESS' | 'NO_ANSWER' | 'USER_BUSY' | 'DESTINATION_OUT_OF_ORDER' | string;
    QueueMemberCIDName: string; // +33612345678
    QueueMemberCIDNumber: string; // 0612345678
    QueueMemberJoinedTime: TSSecString; // "1559904736"
    QueueMemberLeavingTime: TSSecString; // '1559904796"
    QueueBridgeTerminatedTime: TSSecString; // '1559904796"
    QueueMemberSessionUUID: string; // UUID
    QueueMemberDNIS: string;
    QueueMemberUUID: string; // UUID
    Ts: string; // '1559904796"
}
/**
 * V1 + V2
 */
export interface Details {
    Description: string; // OVH label
    Id: string; // instAsString OVH id
    IdBillingAccount: string; // instAsString IdBillingAccount
    SimultaneousLine: string; // instAsString
    Type: 'easyHunting' | string;
}

/**
 * For API V2
 */
export interface EventSession {
    id: string; // "BkfFH11M1cf7",
    creation: string, // "2019-06-07T11:40:16.036197406+02:00",
    lastUpdate: string, //"2019-06-07T11:40:16.03650895+02:00",
    lastConnection: string, //"2019-06-07T11:40:16.036199867+02:00"
}

export interface IevToken {
    billingAccount: string;
    token: string;
    //    session: string;
}

export interface IEvTokenGroup {
    groups: IevToken[];
    session: string;
}

export interface IOvhEventListener {
    on(event: "message", listener: (msg: IVoipEventV2) => void): this;
    redis(redis: IHandyRedis, channel: string): IOvhEventListener;
    listen(): Promise<any>
}
