import { ApiCommon } from '@ovh-api/common';
/**
 * Elasticsearch alias
 */
export interface DbaasLogsAlias {
  /**
   * Alias UUID
   *
   */
  aliasId?: string;
  /**
   * Input creation
   *
   */
  createdAt?: string;
  /**
   * Alias description
   *
   */
  description?: string;
  /**
   * Indicates if you are allowed to edit entry
   *
   */
  isEditable?: boolean;
  /**
   * Indicates if you are allowed to share entry
   *
   */
  isShareable?: boolean;
  /**
   * Alias name
   *
   */
  name?: string;
  /**
   * Associated DBaaS Logs option
   *
   */
  optionId?: string;
  /**
   * Input last update
   *
   */
  updatedAt?: string;
}
/**
 * Network allowed to join input
 */
export interface DbaasLogsAllowedNetwork {
  /**
   * Network UUID
   *
   */
  allowedNetworkId?: string;
  /**
   * IP block
   *
   */
  network?: string;
}
/**
 * Stream archive
 */
export interface DbaasLogsArchive {
  /**
   * Archive UUID
   *
   */
  archiveId?: string;
  /**
   * Create date
   *
   */
  createdAt?: string;
  /**
   * Filename
   *
   */
  filename?: string;
  /**
   * MD5 checksum
   *
   */
  md5?: string;
  /**
   * Retrieval delay
   *
   */
  retrievalDelay?: Number;
  /**
   * Retrieval state
   *
   */
  retrievalState?: DbaasLogsArchiveRetrievalStateEnum;
  /**
   * sha256 checksum
   *
   */
  sha256?: string;
  /**
   * File size in bytes
   *
   */
  size?: Number;
}
/**
 * Possible values for ArchiveRetrievalStateEnum
 */
export type DbaasLogsArchiveRetrievalStateEnum = 'sealed' | 'unsealed' | 'unsealing';
/**
 * Stream archive url
 */
export interface DbaasLogsArchiveUrl {
  /**
   * Temporary URL expiration date
   *
   */
  expirationDate?: string;
  /**
   * Temporary URL to get archive
   *
   */
  url?: string;
}
/**
 * Cluster
 */
export interface DbaasLogsCluster {
  /**
   * Cluster UUID
   *
   */
  clusterId?: string;
  /**
   * Cluster type
   *
   */
  clusterType?: DbaasLogsClusterClusterTypeEnum;
  /**
   * PEM for dedicated inputs
   *
   */
  dedicatedInputPEM?: string;
  /**
   * PEM for direct inputs
   *
   */
  directInputPEM?: string;
  /**
   * Hostname
   *
   */
  hostname?: string;
  /**
   * All content generated by given service will be placed on this cluster
   *
   */
  isDefault?: boolean;
  /**
   * Allow given service to perform advanced operations on cluster
   *
   */
  isUnlocked?: boolean;
  /**
   * Data center localization
   *
   */
  region?: DbaasLogsClusterRegionEnum;
}
/**
 * Cluster allowed network
 */
export interface DbaasLogsClusterAllowedNetwork {
  /**
   * Network UUID
   *
   */
  allowedNetworkId?: string;
  /**
   * Flow type
   *
   */
  flowType?: DbaasLogsClusterAllowedNetworkFlowTypeEnum;
  /**
   * IP block
   *
   */
  network?: string;
}
/**
 * Possible values for ClusterAllowedNetworkFlowTypeEnum
 */
export type DbaasLogsClusterAllowedNetworkFlowTypeEnum = 'ALL' | 'DIRECT_INPUT' | 'QUERY';
/**
 * Possible values for ClusterClusterTypeEnum
 */
export type DbaasLogsClusterClusterTypeEnum = 'DEDICATED' | 'PRO' | 'TRIAL';
/**
 * Possible values for ClusterRegionEnum
 */
export type DbaasLogsClusterRegionEnum = 'BHS' | 'GRA' | 'P-19' | 'RBX' | 'SBG';
/**
 * Graylog dashboard
 */
export interface DbaasLogsDashboard {
  /**
   * Dashboard creation
   *
   */
  createdAt?: string;
  /**
   * Dashboard UUID
   *
   */
  dashboardId?: string;
  /**
   * Dashboard description
   *
   */
  description?: string;
  /**
   * Indicates if you are allowed to edit entry
   *
   */
  isEditable?: boolean;
  /**
   * Indicates if you are allowed to share entry
   *
   */
  isShareable?: boolean;
  /**
   * Associated DBaaS Logs option
   *
   */
  optionId?: string;
  /**
   * Dashboard description
   *
   */
  title?: string;
  /**
   * Dashboard last update
   *
   */
  updatedAt?: string;
}
/**
 * Input engine
 */
export interface DbaasLogsEngine {
  /**
   * Input engine UUID
   *
   */
  engineId?: string;
  /**
   * Indicates if engine will soon not be supported
   *
   */
  isDeprecated?: boolean;
  /**
   * Software name
   *
   */
  name?: DbaasLogsEngineNameEnum;
  /**
   * Software version
   *
   */
  version?: string;
}
/**
 * Possible values for EngineNameEnum
 */
export type DbaasLogsEngineNameEnum = 'FLOWGGER' | 'LOGSTASH' | 'TEST';
/**
 * Flowgger configuration
 */
export interface DbaasLogsFlowggerConfiguration {
  /**
   * Type of format to decode
   *
   */
  logFormat?: DbaasLogsFlowggerConfigurationLogFormatEnum;
  /**
   * Indicates how messages are delimited
   *
   */
  logFraming?: DbaasLogsFlowggerConfigurationLogFramingEnum;
}
/**
 * Possible values for FlowggerConfigurationLogFormatEnum
 */
export type DbaasLogsFlowggerConfigurationLogFormatEnum = 'CAPNP' | 'GELF' | 'LTSV' | 'RFC5424';
/**
 * Possible values for FlowggerConfigurationLogFramingEnum
 */
export type DbaasLogsFlowggerConfigurationLogFramingEnum = 'CAPNP' | 'LINE' | 'NUL' | 'SYSLEN';
/**
 * Elasticsearch index
 */
export interface DbaasLogsIndex {
  /**
   * Notify if size is near 80, 90 or 100 %
   *
   */
  alertNotifyEnabled?: boolean;
  /**
   * Index creation
   *
   */
  createdAt?: string;
  /**
   * Index description
   *
   */
  description?: string;
  /**
   * Index UUID
   *
   */
  indexId?: string;
  /**
   * Indicates if you are allowed to edit entry
   *
   */
  isEditable?: boolean;
  /**
   * Indicates if you are allowed to share entry
   *
   */
  isShareable?: boolean;
  /**
   * Maximum index size (in bytes)
   *
   */
  maxSize?: Number;
  /**
   * Index name
   *
   */
  name?: string;
  /**
   * Associated DBaaS Logs option
   *
   */
  optionId?: string;
  /**
   * Index last update
   *
   */
  updatedAt?: string;
}
/**
 * Input
 */
export interface DbaasLogsInput {
  /**
   * Input creation
   *
   */
  createdAt?: string;
  /**
   * Input description
   *
   */
  description?: string;
  /**
   * Input engine UUID
   *
   */
  engineId?: string;
  /**
   * Port
   *
   */
  exposedPort?: string;
  /**
   * Hostname
   *
   */
  hostname?: string;
  /**
   * Input ID
   *
   */
  inputId?: string;
  /**
   * Indicate if input need to be restarted
   *
   */
  isRestartRequired?: boolean;
  /**
   * Associated DBaaS Logs option
   *
   */
  optionId?: string;
  /**
   * Input IP address
   *
   */
  publicAddress?: string;
  /**
   * Force only one instance
   *
   */
  singleInstanceEnabled?: boolean;
  /**
   * Input SSL certificate
   *
   */
  sslCertificate?: string;
  /**
   * init: configuration required, pending: ready to start, running: available
   *
   */
  status?: DbaasLogsInputStatusEnum;
  /**
   * Associated Graylog stream
   *
   */
  streamId?: string;
  /**
   * Input title
   *
   */
  title?: string;
  /**
   * Input last update
   *
   */
  updatedAt?: string;
}
/**
 * Action on input
 */
export interface DbaasLogsInputAction {
  /**
   * Indicates if action is allowed
   *
   */
  isAllowed?: boolean;
  /**
   * Action type
   *
   */
  type?: DbaasLogsInputActionTypeEnum;
}
/**
 * Possible values for InputActionTypeEnum
 */
export type DbaasLogsInputActionTypeEnum = 'DESTROY' | 'END' | 'LOG' | 'RESTART' | 'START' | 'TEST';
/**
 * Possible values for InputStatusEnum
 */
export type DbaasLogsInputStatusEnum = 'INIT' | 'PENDING' | 'PROCESSING' | 'RUNNING';
/**
 * Logstash configuration
 */
export interface DbaasLogsLogstashConfiguration {
  /**
   * The filter section of logstash.conf
   *
   */
  filterSection?: string;
  /**
   * The filter section of logstash.conf
   *
   */
  inputSection?: string;
  /**
   * The list of customs Grok patterns
   *
   */
  patternSection?: string;
}
/**
 * Member
 */
export interface DbaasLogsMember {
  /**
   * Custom note
   *
   */
  note?: string;
  /**
   * Username on DBaaS Logs
   *
   */
  username?: string;
}
/**
 * DBaaS Logs offer
 */
export interface DbaasLogsOffer {
  /**
   * Current number of alias booked
   *
   */
  curNbAlias?: Number;
  /**
   * Current number of dashboard booked
   *
   */
  curNbDashboard?: Number;
  /**
   * Current number of index booked
   *
   */
  curNbIndex?: Number;
  /**
   * Current number of input booked
   *
   */
  curNbInput?: Number;
  /**
   * Current number of role booked
   *
   */
  curNbRole?: Number;
  /**
   * Current number of stream booked
   *
   */
  curNbStream?: Number;
  /**
   * Number of GB stored per month included
   *
   */
  esStorage?: Number;
  /**
   * Maximum number of alias allowed
   *
   */
  maxNbAlias?: Number;
  /**
   * Maximum number of dashboard allowed
   *
   */
  maxNbDashboard?: Number;
  /**
   * Maximum number of index allowed
   *
   */
  maxNbIndex?: Number;
  /**
   * Maximum number of input allowed
   *
   */
  maxNbInput?: Number;
  /**
   * Maximum number of role allowed
   *
   */
  maxNbRole?: Number;
  /**
   * Maximum number of stream allowed
   *
   */
  maxNbStream?: Number;
  /**
   * Option unique reference
   *
   */
  reference?: string;
  /**
   * Data retention in hours
   *
   */
  retention?: Number;
}
/**
 * Asynchronous operation
 */
export interface DbaasLogsOperation {
  /**
   * Alias used
   *
   */
  aliasId?: string;
  /**
   * Operation creation
   *
   */
  createdAt?: string;
  /**
   * Dashboard used
   *
   */
  dashboardId?: string;
  /**
   * Index used
   *
   */
  indexId?: string;
  /**
   * Input used
   *
   */
  inputId?: string;
  /**
   * Operation UUID
   *
   */
  operationId?: string;
  /**
   * Option used
   *
   */
  optionId?: string;
  /**
   * Role used
   *
   */
  roleId?: string;
  /**
   * Operation status
   *
   */
  state?: DbaasLogsOperationStateEnum;
  /**
   * Stream used
   *
   */
  streamId?: string;
  /**
   * Operation last update
   *
   */
  updatedAt?: string;
}
/**
 * Possible values for OperationStateEnum
 */
export type DbaasLogsOperationStateEnum = 'FAILURE' | 'PENDING' | 'RECEIVED' | 'RETRY' | 'REVOKED' | 'RUNNING' | 'STARTED' | 'SUCCESS';
/**
 * DBaaS Logs option
 */
export interface DbaasLogsOption {
  /**
   * Service creation
   *
   */
  createdAt?: string;
  /**
   * Current number of alias booked
   *
   */
  curNbAlias?: Number;
  /**
   * Current number of dashboard booked
   *
   */
  curNbDashboard?: Number;
  /**
   * Current number of index booked
   *
   */
  curNbIndex?: Number;
  /**
   * Current number of input booked
   *
   */
  curNbInput?: Number;
  /**
   * Current number of role booked
   *
   */
  curNbRole?: Number;
  /**
   * Current number of stream booked
   *
   */
  curNbStream?: Number;
  /**
   * Index size in bytes
   *
   */
  indexSize?: Number;
  /**
   * Maximum number of alias allowed
   *
   */
  maxNbAlias?: Number;
  /**
   * Maximum number of dashboard allowed
   *
   */
  maxNbDashboard?: Number;
  /**
   * Maximum number of index allowed
   *
   */
  maxNbIndex?: Number;
  /**
   * Maximum number of input allowed
   *
   */
  maxNbInput?: Number;
  /**
   * Maximum number of role allowed
   *
   */
  maxNbRole?: Number;
  /**
   * Maximum number of stream allowed
   *
   */
  maxNbStream?: Number;
  /**
   * Option UUID
   *
   */
  optionId?: string;
  /**
   * Option unique reference
   *
   */
  reference?: string;
  /**
   * Option state
   *
   */
  state?: DbaasLogsOptionStateEnum;
  /**
   * Service last update
   *
   */
  updatedAt?: string;
}
/**
 * Possible values for OptionStateEnum
 */
export type DbaasLogsOptionStateEnum = 'DISABLED' | 'ENABLED';
/**
 * Role permission
 */
export interface DbaasLogsPermission {
  /**
   * Associated Elasticsearch alias
   *
   */
  aliasId?: string;
  /**
   * Associated Graylog dashboard
   *
   */
  dashboardId?: string;
  /**
   * Associated Elasticsearch index
   *
   */
  indexId?: string;
  /**
   * Permission UUID
   *
   */
  permissionId?: string;
  /**
   * Associated Graylog stream
   *
   */
  streamId?: string;
}
/**
 * Possible values for PermissionDashboardPermissionTypeEnum
 */
export type DbaasLogsPermissionDashboardPermissionTypeEnum = 'READ_ONLY' | 'READ_WRITE';
/**
 * Possible values for PermissionIndexPermissionTypeEnum
 */
export type DbaasLogsPermissionIndexPermissionTypeEnum = 'READ_ONLY' | 'READ_WRITE';
/**
 * DBaaS Logs offer
 */
export interface DbaasLogsPublicOffer {
  /**
   * Number of GB stored per month included
   *
   */
  esStorage?: Number;
  /**
   * Maximum number of alias allowed
   *
   */
  maxNbAlias?: Number;
  /**
   * Maximum number of dashboard allowed
   *
   */
  maxNbDashboard?: Number;
  /**
   * Maximum number of index allowed
   *
   */
  maxNbIndex?: Number;
  /**
   * Maximum number of input allowed
   *
   */
  maxNbInput?: Number;
  /**
   * Maximum number of role allowed
   *
   */
  maxNbRole?: Number;
  /**
   * Maximum number of stream allowed
   *
   */
  maxNbStream?: Number;
  /**
   * Option unique reference
   *
   */
  reference?: string;
}
/**
 * DBaaS Logs quota
 */
export interface DbaasLogsQuota {
  /**
   * Current number of alias booked
   *
   */
  curNbAlias?: Number;
  /**
   * Current number of dashboard booked
   *
   */
  curNbDashboard?: Number;
  /**
   * Current number of index booked
   *
   */
  curNbIndex?: Number;
  /**
   * Current number of input booked
   *
   */
  curNbInput?: Number;
  /**
   * Current number of role booked
   *
   */
  curNbRole?: Number;
  /**
   * Current number of stream booked
   *
   */
  curNbStream?: Number;
  /**
   * Maximum number of alias allowed
   *
   */
  maxNbAlias?: Number;
  /**
   * Maximum number of dashboard allowed
   *
   */
  maxNbDashboard?: Number;
  /**
   * Maximum number of index allowed
   *
   */
  maxNbIndex?: Number;
  /**
   * Maximum number of input allowed
   *
   */
  maxNbInput?: Number;
  /**
   * Maximum number of role allowed
   *
   */
  maxNbRole?: Number;
  /**
   * Maximum number of stream allowed
   *
   */
  maxNbStream?: Number;
}
/**
 * Role
 */
export interface DbaasLogsRole {
  /**
   * Role description
   *
   */
  description?: string;
  /**
   * Role name
   *
   */
  name?: string;
  /**
   * Associated DBaaS Logs option
   *
   */
  optionId?: string;
  /**
   * Role UUID
   *
   */
  roleId?: string;
}
/**
 * Service
 */
export interface DbaasLogsService {
  /**
   * Service creation
   *
   */
  createdAt?: string;
  /**
   * Service custom name
   *
   */
  displayName?: string;
  /**
   * Is capped plan enabled?
   *
   */
  isCapped?: boolean;
  /**
   * Service name
   *
   */
  serviceName?: string;
  /**
   * Service state
   *
   */
  state?: DbaasLogsServiceStateEnum;
  /**
   * Service last update
   *
   */
  updatedAt?: string;
  /**
   * Username on DBaaS Logs
   *
   */
  username?: string;
}
/**
 * Metrics access
 */
export interface DbaasLogsServiceMetric {
  /**
   * Metrics server url
   *
   */
  host?: string;
  /**
   * Metrics credentials
   *
   */
  token?: string;
}
/**
 * Possible values for ServiceStateEnum
 */
export type DbaasLogsServiceStateEnum = 'DISABLED' | 'ENABLED' | 'INIT' | 'TO_CONFIG';
/**
 * Graylog stream
 */
export interface DbaasLogsStream {
  /**
   * Indicates if the current user can create alert on the stream
   *
   */
  canAlert?: boolean;
  /**
   * Cold storage compression method
   *
   */
  coldStorageCompression?: DbaasLogsStreamColdStorageCompressionEnum;
  /**
   * ColdStorage content
   *
   */
  coldStorageContent?: DbaasLogsStreamColdStorageContentEnum;
  /**
   * Is Cold storage enabled?
   *
   */
  coldStorageEnabled?: boolean;
  /**
   * Notify on new Cold storage archive
   *
   */
  coldStorageNotifyEnabled?: boolean;
  /**
   * Cold storage retention in year
   *
   */
  coldStorageRetention?: Number;
  /**
   * ColdStorage destination
   *
   */
  coldStorageTarget?: DbaasLogsStreamColdStorageTargetEnum;
  /**
   * Stream creation
   *
   */
  createdAt?: string;
  /**
   * Stream description
   *
   */
  description?: string;
  /**
   * Enable ES indexing
   *
   */
  indexingEnabled?: boolean;
  /**
   * Indicates if you are allowed to edit entry
   *
   */
  isEditable?: boolean;
  /**
   * Indicates if you are allowed to share entry
   *
   */
  isShareable?: boolean;
  /**
   * Number of coldstored archives
   *
   */
  nbArchive?: Number;
  /**
   * Associated DBaaS Logs option
   *
   */
  optionId?: string;
  /**
   * Parent stream id
   *
   */
  parentStreamId?: string;
  /**
   * Stream UUID
   *
   */
  streamId?: string;
  /**
   * Stream description
   *
   */
  title?: string;
  /**
   * Stream last update
   *
   */
  updatedAt?: string;
  /**
   * Enable Websocket
   *
   */
  webSocketEnabled?: boolean;
}
/**
 * Alert condition
 */
export interface DbaasLogsStreamAlertCondition {
  /**
   * Stream alert condition UUID
   *
   */
  alertId?: string;
  /**
   * Backlog size
   *
   */
  backlog?: Number;
  /**
   * Alert condition type
   *
   */
  conditionType?: DbaasLogsStreamAlertConditionConditionTypeEnum;
  /**
   * Constraint type
   *
   */
  constraintType?: DbaasLogsStreamAlertConditionConstraintTypeEnum;
  /**
   * Field name
   *
   */
  field?: string;
  /**
   * Grace period in minutes
   *
   */
  grace?: Number;
  /**
   * Query filter
   *
   */
  queryFilter?: string;
  /**
   * Repeat notifications
   *
   */
  repeatNotificationsEnabled?: boolean;
  /**
   * Threshold
   *
   */
  threshold?: Number;
  /**
   * Threshold condition
   *
   */
  thresholdType?: DbaasLogsStreamAlertConditionThresholdTypeEnum;
  /**
   * Time lapse in minutes
   *
   */
  time?: Number;
  /**
   * Condition label
   *
   */
  title?: string;
  /**
   * Field value
   *
   */
  value?: string;
}
/**
 * Possible values for StreamAlertConditionConditionTypeEnum
 */
export type DbaasLogsStreamAlertConditionConditionTypeEnum = 'FIELD_CONTENT_VALUE' | 'FIELD_VALUE' | 'MESSAGE_COUNT';
/**
 * Possible values for StreamAlertConditionConstraintTypeEnum
 */
export type DbaasLogsStreamAlertConditionConstraintTypeEnum = 'MAX' | 'MEAN' | 'MIN' | 'STDDEV' | 'SUM';
/**
 * Possible values for StreamAlertConditionThresholdTypeEnum
 */
export type DbaasLogsStreamAlertConditionThresholdTypeEnum = 'HIGHER' | 'LESS' | 'LOWER' | 'MORE';
/**
 * Possible values for StreamColdStorageCompressionEnum
 */
export type DbaasLogsStreamColdStorageCompressionEnum = 'DEFLATED' | 'GZIP' | 'LZMA' | 'ZSTD';
/**
 * Possible values for StreamColdStorageContentEnum
 */
export type DbaasLogsStreamColdStorageContentEnum = 'ALL' | 'GELF' | 'PLAIN';
/**
 * Possible values for StreamColdStorageTargetEnum
 */
export type DbaasLogsStreamColdStorageTargetEnum = 'PCA' | 'PCS';
/**
 * Stream rule
 */
export interface DbaasLogsStreamRule {
  /**
   * Field name
   *
   */
  field?: string;
  /**
   * Invert condition
   *
   */
  isInverted?: boolean;
  /**
   * Field operator
   *
   */
  operator?: DbaasLogsStreamRuleOperatorEnum;
  /**
   * Stream rule UUID
   *
   */
  ruleId?: string;
  /**
   * Field value
   *
   */
  value?: string;
}
/**
 * Possible values for StreamRuleOperatorEnum
 */
export type DbaasLogsStreamRuleOperatorEnum = 'FIELD_PRESENCE' | 'GREATER_THAN' | 'MATCH_EXACTLY' | 'SMALLER_THAN';
/**
 * Temporary url informations
 */
export interface DbaasLogsTemporaryLogsLink {
  /**
   * Temporary url expiration date
   *
   */
  expirationDate?: string;
  /**
   * Temporary url
   *
   */
  url?: string;
}
/**
 * Config test results
 */
export interface DbaasLogsTestResult {
  /**
   * Standard error
   *
   */
  stderr?: string;
  /**
   * Standard output
   *
   */
  stdout?: string;
  /**
   * Last config test update
   *
   */
  updatedAt?: string;
}
/**
 * Token
 */
export interface DbaasLogsToken {
  /**
   * Cluster UUID
   *
   */
  clusterId?: string;
  /**
   * Token creation
   *
   */
  createdAt?: string;
  /**
   * Token name
   *
   */
  name?: string;
  /**
   * Token UUID
   *
   */
  tokenId?: string;
  /**
   * Token last update
   *
   */
  updatedAt?: string;
  /**
   * Token value
   *
   */
  value?: string;
}
/**
 * Web address
 */
export interface DbaasLogsUrl {
  /**
   * Web URI
   *
   */
  address?: string;
  /**
   * Service type
   *
   */
  type?: DbaasLogsUrlTypeEnum;
}
/**
 * Possible values for UrlTypeEnum
 */
export type DbaasLogsUrlTypeEnum = 'CONSOLE' | 'ELASTICSEARCH_API' | 'GRAYLOG_API' | 'GRAYLOG_WEBUI' | 'HTTP_GELF' | 'HTTP_TLS_GELF' | 'KIBANA_WEBUI' | 'SERVICE_DOMAIN' | 'TCP_BEATS' | 'TCP_CAP_N_PROTO' | 'TCP_GELF' | 'TCP_LTSV_LINE' | 'TCP_LTSV_NUL' | 'TCP_RFC5424' | 'TCP_TLS_BEATS' | 'TCP_TLS_CAP_N_PROTO' | 'TCP_TLS_GELF' | 'TCP_TLS_LTSV_LINE' | 'TCP_TLS_LTSV_NUL' | 'TCP_TLS_RFC5424' | 'UDP_CAP_N_PROTO' | 'UDP_GELF' | 'UDP_LTSV_LINE' | 'UDP_LTSV_NUL' | 'UDP_RFC5424' | 'WEB_SOCKET';
/**
 * Map a possible renew for a specific service
 */
export interface ServiceRenewType {
  /**
   * The service is automatically renewed
   *
   */
  automatic?: boolean;
  /**
   * The service will be deleted at expiration
   *
   */
  deleteAtExpiration?: boolean;
  /**
   * The service forced to be renewed
   *
   */
  forced?: boolean;
  /**
   * The service needs to be manually renewed and paid
   *
   */
  manualPayment?: boolean;
  /**
   * period of renew in month
   *
   */
  period?: Number;
}
/**
 * Detailed renewal type of a service
 */
export type ServiceRenewalTypeEnum = 'automaticForcedProduct' | 'automaticV2012' | 'automaticV2014' | 'automaticV2016' | 'manual' | 'oneShot' | 'option';
/**
 * 
 */
export type ServiceStateEnum = 'expired' | 'inCreation' | 'ok' | 'pendingDebt' | 'unPaid';
/**
 * Details about a Service
 */
export interface ServicesService {
  /**
   * Indicates that the service can be set up to be deleted at expiration
   *
   */
  canDeleteAtExpiration?: boolean;
  /**
   */
  contactAdmin?: string;
  /**
   */
  contactBilling?: string;
  /**
   */
  contactTech?: string;
  /**
   */
  creation?: string;
  /**
   */
  domain?: string;
  /**
   */
  engagedUpTo?: string;
  /**
   */
  expiration?: string;
  /**
   * All the possible renew period of your service in month
   *
   */
  possibleRenewPeriod?: Number[];
  /**
   * Way of handling the renew
   *
   */
  renew?: ServiceRenewType;
  /**
   */
  renewalType?: ServiceRenewalTypeEnum;
  /**
   */
  serviceId?: Number;
  /**
   */
  status?: ServiceStateEnum;
}
type PathsDbaasLogsGET = '/dbaas/logs' | 
'/dbaas/logs/input/engine' | 
'/dbaas/logs/input/engine/{engineId}' | 
'/dbaas/logs/offer/{reference}' | 
'/dbaas/logs/{serviceName}' | 
'/dbaas/logs/{serviceName}/cluster' | 
'/dbaas/logs/{serviceName}/cluster/{clusterId}' | 
'/dbaas/logs/{serviceName}/cluster/{clusterId}/allowedNetwork' | 
'/dbaas/logs/{serviceName}/cluster/{clusterId}/allowedNetwork/{allowedNetworkId}' | 
'/dbaas/logs/{serviceName}/input' | 
'/dbaas/logs/{serviceName}/input/{inputId}' | 
'/dbaas/logs/{serviceName}/input/{inputId}/action' | 
'/dbaas/logs/{serviceName}/input/{inputId}/allowedNetwork' | 
'/dbaas/logs/{serviceName}/input/{inputId}/allowedNetwork/{allowedNetworkId}' | 
'/dbaas/logs/{serviceName}/input/{inputId}/configtest/result' | 
'/dbaas/logs/{serviceName}/input/{inputId}/configuration/flowgger' | 
'/dbaas/logs/{serviceName}/input/{inputId}/configuration/logstash' | 
'/dbaas/logs/{serviceName}/input/{inputId}/url' | 
'/dbaas/logs/{serviceName}/metrics' | 
'/dbaas/logs/{serviceName}/offer' | 
'/dbaas/logs/{serviceName}/operation' | 
'/dbaas/logs/{serviceName}/operation/{operationId}' | 
'/dbaas/logs/{serviceName}/option' | 
'/dbaas/logs/{serviceName}/option/{optionId}' | 
'/dbaas/logs/{serviceName}/output/elasticsearch/alias' | 
'/dbaas/logs/{serviceName}/output/elasticsearch/alias/{aliasId}' | 
'/dbaas/logs/{serviceName}/output/elasticsearch/alias/{aliasId}/index' | 
'/dbaas/logs/{serviceName}/output/elasticsearch/alias/{aliasId}/stream' | 
'/dbaas/logs/{serviceName}/output/elasticsearch/alias/{aliasId}/url' | 
'/dbaas/logs/{serviceName}/output/elasticsearch/index' | 
'/dbaas/logs/{serviceName}/output/elasticsearch/index/{indexId}' | 
'/dbaas/logs/{serviceName}/output/elasticsearch/index/{indexId}/url' | 
'/dbaas/logs/{serviceName}/output/graylog/dashboard' | 
'/dbaas/logs/{serviceName}/output/graylog/dashboard/{dashboardId}' | 
'/dbaas/logs/{serviceName}/output/graylog/dashboard/{dashboardId}/url' | 
'/dbaas/logs/{serviceName}/output/graylog/stream' | 
'/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}' | 
'/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/alert' | 
'/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/alert/{alertId}' | 
'/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/archive' | 
'/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/archive/{archiveId}' | 
'/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/rule' | 
'/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/rule/{ruleId}' | 
'/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/url' | 
'/dbaas/logs/{serviceName}/quota' | 
'/dbaas/logs/{serviceName}/role' | 
'/dbaas/logs/{serviceName}/role/{roleId}' | 
'/dbaas/logs/{serviceName}/role/{roleId}/member' | 
'/dbaas/logs/{serviceName}/role/{roleId}/member/{username}' | 
'/dbaas/logs/{serviceName}/role/{roleId}/permission' | 
'/dbaas/logs/{serviceName}/role/{roleId}/permission/{permissionId}' | 
'/dbaas/logs/{serviceName}/serviceInfos' | 
'/dbaas/logs/{serviceName}/token' | 
'/dbaas/logs/{serviceName}/token/{tokenId}' | 
'/dbaas/logs/{serviceName}/url';

type PathsDbaasLogsPUT = '/dbaas/logs/{serviceName}' | 
'/dbaas/logs/{serviceName}/input/{inputId}' | 
'/dbaas/logs/{serviceName}/input/{inputId}/configuration/flowgger' | 
'/dbaas/logs/{serviceName}/input/{inputId}/configuration/logstash' | 
'/dbaas/logs/{serviceName}/output/elasticsearch/alias/{aliasId}' | 
'/dbaas/logs/{serviceName}/output/elasticsearch/index/{indexId}' | 
'/dbaas/logs/{serviceName}/output/graylog/dashboard/{dashboardId}' | 
'/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}' | 
'/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/alert/{alertId}' | 
'/dbaas/logs/{serviceName}/role/{roleId}' | 
'/dbaas/logs/{serviceName}/role/{roleId}/member/{username}' | 
'/dbaas/logs/{serviceName}/serviceInfos';

type PathsDbaasLogsPOST = '/dbaas/logs/{serviceName}/changeContact' | 
'/dbaas/logs/{serviceName}/cluster/{clusterId}/allowedNetwork' | 
'/dbaas/logs/{serviceName}/input' | 
'/dbaas/logs/{serviceName}/input/{inputId}/allowedNetwork' | 
'/dbaas/logs/{serviceName}/input/{inputId}/configtest' | 
'/dbaas/logs/{serviceName}/input/{inputId}/end' | 
'/dbaas/logs/{serviceName}/input/{inputId}/logs/url' | 
'/dbaas/logs/{serviceName}/input/{inputId}/restart' | 
'/dbaas/logs/{serviceName}/input/{inputId}/start' | 
'/dbaas/logs/{serviceName}/option/{optionId}/terminate' | 
'/dbaas/logs/{serviceName}/output/elasticsearch/alias' | 
'/dbaas/logs/{serviceName}/output/elasticsearch/alias/{aliasId}/index' | 
'/dbaas/logs/{serviceName}/output/elasticsearch/alias/{aliasId}/stream' | 
'/dbaas/logs/{serviceName}/output/elasticsearch/index' | 
'/dbaas/logs/{serviceName}/output/graylog/dashboard' | 
'/dbaas/logs/{serviceName}/output/graylog/dashboard/{dashboardId}/duplicate' | 
'/dbaas/logs/{serviceName}/output/graylog/stream' | 
'/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/alert' | 
'/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/archive/{archiveId}/url' | 
'/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/rule' | 
'/dbaas/logs/{serviceName}/role' | 
'/dbaas/logs/{serviceName}/role/{roleId}/member' | 
'/dbaas/logs/{serviceName}/role/{roleId}/permission/alias' | 
'/dbaas/logs/{serviceName}/role/{roleId}/permission/dashboard' | 
'/dbaas/logs/{serviceName}/role/{roleId}/permission/index' | 
'/dbaas/logs/{serviceName}/role/{roleId}/permission/stream' | 
'/dbaas/logs/{serviceName}/token' | 
'/dbaas/logs/{serviceName}/user/changePassword';

type PathsDbaasLogsDELETE = '/dbaas/logs/{serviceName}/cluster/{clusterId}/allowedNetwork/{allowedNetworkId}' | 
'/dbaas/logs/{serviceName}/input/{inputId}' | 
'/dbaas/logs/{serviceName}/input/{inputId}/allowedNetwork/{allowedNetworkId}' | 
'/dbaas/logs/{serviceName}/output/elasticsearch/alias/{aliasId}' | 
'/dbaas/logs/{serviceName}/output/elasticsearch/alias/{aliasId}/index/{indexId}' | 
'/dbaas/logs/{serviceName}/output/elasticsearch/alias/{aliasId}/stream/{streamId}' | 
'/dbaas/logs/{serviceName}/output/elasticsearch/index/{indexId}' | 
'/dbaas/logs/{serviceName}/output/graylog/dashboard/{dashboardId}' | 
'/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}' | 
'/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/alert/{alertId}' | 
'/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/rule/{ruleId}' | 
'/dbaas/logs/{serviceName}/role/{roleId}' | 
'/dbaas/logs/{serviceName}/role/{roleId}/member/{username}' | 
'/dbaas/logs/{serviceName}/role/{roleId}/permission/{permissionId}' | 
'/dbaas/logs/{serviceName}/token/{tokenId}';

export class ApiDbaasLogs extends ApiCommon {
  constructor(config: {appKey: string, appSecret: string, consumerKey: string}) {
    super(config);
  }
  /**
  Operations about the DBAAS-LOGS service
  List available services
  **/
  public get(path: '/dbaas/logs'): Promise<string[]>;
  /**
  Engine
  Returns details of specified input engine
  **/
  public get(path: '/dbaas/logs/input/engine/{engineId}', pathParams: {engineId: string}): Promise<DbaasLogsEngine>;
  /**
  Engines
  Returns the list of available input engines
  **/
  public get(path: '/dbaas/logs/input/engine'): Promise<string[]>;
  /**
  Token
  Returns the specified token
  **/
  public get(path: '/dbaas/logs/{serviceName}/token/{tokenId}', pathParams: {serviceName: string, tokenId: string}): Promise<DbaasLogsToken>;
  /**
  Tokens
  Returns the list of service tokens
  **/
  public get(path: '/dbaas/logs/{serviceName}/token', pathParams: {serviceName: string}): Promise<string[]>;
  /**
  ServiceUrls
  Returns platform useful urls.
  **/
  public get(path: '/dbaas/logs/{serviceName}/url', pathParams: {serviceName: string}): Promise<DbaasLogsUrl[]>;
  /**
  Roles
  Returns the list of roles
  **/
  public get(path: '/dbaas/logs/{serviceName}/role', pathParams: {serviceName: string}): Promise<string[]>;
  /**
  Role
  Returns details of specified role
  **/
  public get(path: '/dbaas/logs/{serviceName}/role/{roleId}', pathParams: {serviceName: string, roleId: string}): Promise<DbaasLogsRole>;
  /**
  RoleMember
  Returns the member metadata
  **/
  public get(path: '/dbaas/logs/{serviceName}/role/{roleId}/member/{username}', pathParams: {serviceName: string, roleId: string, username: string}): Promise<DbaasLogsMember>;
  /**
  RoleMembers
  Returns the member list of specified role
  **/
  public get(path: '/dbaas/logs/{serviceName}/role/{roleId}/member', pathParams: {serviceName: string, roleId: string}): Promise<string[]>;
  /**
  RolePermissions
  Returns the list of permissions of specified role
  **/
  public get(path: '/dbaas/logs/{serviceName}/role/{roleId}/permission', pathParams: {serviceName: string, roleId: string}): Promise<string[]>;
  /**
  RolePermission
  Returns details of specified permission
  **/
  public get(path: '/dbaas/logs/{serviceName}/role/{roleId}/permission/{permissionId}', pathParams: {serviceName: string, roleId: string, permissionId: string}): Promise<DbaasLogsPermission[]>;
  /**
  Service Metrics
  Returns Metrics credentials
  **/
  public get(path: '/dbaas/logs/{serviceName}/metrics', pathParams: {serviceName: string}): Promise<DbaasLogsServiceMetric>;
  /**
  ServiceQuota
  Returns the overall quota limits
  **/
  public get(path: '/dbaas/logs/{serviceName}/quota', pathParams: {serviceName: string}): Promise<DbaasLogsQuota>;
  /**
  Operation
  Returns details of specified operation
  **/
  public get(path: '/dbaas/logs/{serviceName}/operation/{operationId}', pathParams: {serviceName: string, operationId: string}): Promise<DbaasLogsOperation>;
  /**
  Operations
  Latest operations
  **/
  public get(path: '/dbaas/logs/{serviceName}/operation', pathParams: {serviceName: string}): Promise<string[]>;
  /**
  StreamUrls
  Returns the list of urls of specified graylog stream
  **/
  public get(path: '/dbaas/logs/{serviceName}/output/elasticsearch/index/{indexId}/url', pathParams: {serviceName: string, indexId: string}): Promise<DbaasLogsUrl[]>;
  /**
  Index
  Returns specified elasticsearch index
  **/
  public get(path: '/dbaas/logs/{serviceName}/output/elasticsearch/index/{indexId}', pathParams: {serviceName: string, indexId: string}): Promise<DbaasLogsIndex>;
  /**
  Indexes
  Returns the list of elasticsearch indexes
  **/
  public get(path: '/dbaas/logs/{serviceName}/output/elasticsearch/index', pathParams: {serviceName: string}): Promise<string[]>;
  /**
  Aliases
  Returns the list of alias for connected user
  **/
  public get(path: '/dbaas/logs/{serviceName}/output/elasticsearch/alias', pathParams: {serviceName: string}): Promise<string[]>;
  /**
  Alias
  Returns specified elasticsearch alias
  **/
  public get(path: '/dbaas/logs/{serviceName}/output/elasticsearch/alias/{aliasId}', pathParams: {serviceName: string, aliasId: string}): Promise<DbaasLogsAlias>;
  /**
  StreamUrls
  Returns the list of urls of specified graylog stream
  **/
  public get(path: '/dbaas/logs/{serviceName}/output/elasticsearch/alias/{aliasId}/url', pathParams: {serviceName: string, aliasId: string}): Promise<DbaasLogsUrl[]>;
  /**
  AliasStreams
  Returns the list of graylog streams attached to specified
        elasticsearch alias
  **/
  public get(path: '/dbaas/logs/{serviceName}/output/elasticsearch/alias/{aliasId}/stream', pathParams: {serviceName: string, aliasId: string}): Promise<string[]>;
  /**
  AliasStreams
  Returns the list of elasticsearch indexes attached to specified
        elasticsearch alias
  **/
  public get(path: '/dbaas/logs/{serviceName}/output/elasticsearch/alias/{aliasId}/index', pathParams: {serviceName: string, aliasId: string}): Promise<string[]>;
  /**
  Stream
  Returns details of specified graylog stream
  **/
  public get(path: '/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}', pathParams: {serviceName: string, streamId: string}): Promise<DbaasLogsStream>;
  /**
  Streams
  Returns the list of archives
  **/
  public get(path: '/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/archive', pathParams: {serviceName: string, streamId: string}): Promise<string[]>;
  /**
  Streams
  Returns details of specified archive
  **/
  public get(path: '/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/archive/{archiveId}', pathParams: {serviceName: string, streamId: string, archiveId: string}): Promise<DbaasLogsArchive>;
  /**
  StreamRules
  Returns the list of rules of specified graylog stream
  **/
  public get(path: '/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/rule', pathParams: {serviceName: string, streamId: string}): Promise<string[]>;
  /**
  StreamRule
  Returns details of specified graylog stream rule
  **/
  public get(path: '/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/rule/{ruleId}', pathParams: {serviceName: string, streamId: string, ruleId: string}): Promise<DbaasLogsStreamRule[]>;
  /**
  StreamUrls
  Returns the list of urls of specified graylog stream
  **/
  public get(path: '/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/url', pathParams: {serviceName: string, streamId: string}): Promise<DbaasLogsUrl[]>;
  /**
  StreamAlerts
  Returns the list of configured alerts of specified graylog stream
  **/
  public get(path: '/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/alert', pathParams: {serviceName: string, streamId: string}): Promise<string[]>;
  /**
  StreamAlert
  Returns details of specified graylog stream alert
  **/
  public get(path: '/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/alert/{alertId}', pathParams: {serviceName: string, streamId: string, alertId: string}): Promise<DbaasLogsStreamAlertCondition>;
  /**
  Streams
  Returns the list of graylog streams
  **/
  public get(path: '/dbaas/logs/{serviceName}/output/graylog/stream', pathParams: {serviceName: string}): Promise<string[]>;
  /**
  Dashboards
  Returns the list of graylog dashboards
  **/
  public get(path: '/dbaas/logs/{serviceName}/output/graylog/dashboard', pathParams: {serviceName: string}): Promise<string[]>;
  /**
  DashboardUrls
  Returns the list of urls of specified graylog dashboard
  **/
  public get(path: '/dbaas/logs/{serviceName}/output/graylog/dashboard/{dashboardId}/url', pathParams: {serviceName: string, dashboardId: string}): Promise<DbaasLogsUrl[]>;
  /**
  Dashboard
  Returns details of specified graylog dashboard
  **/
  public get(path: '/dbaas/logs/{serviceName}/output/graylog/dashboard/{dashboardId}', pathParams: {serviceName: string, dashboardId: string}): Promise<DbaasLogsDashboard>;
  /**
  FlowggerConfiguration
  Returns the flowgger configuration
  **/
  public get(path: '/dbaas/logs/{serviceName}/input/{inputId}/configuration/flowgger', pathParams: {serviceName: string, inputId: string}): Promise<DbaasLogsFlowggerConfiguration>;
  /**
  LogstashConfiguration
  Returns the logstash configuration
  **/
  public get(path: '/dbaas/logs/{serviceName}/input/{inputId}/configuration/logstash', pathParams: {serviceName: string, inputId: string}): Promise<DbaasLogsLogstashConfiguration>;
  /**
  Input
  Returns details of specified input
  **/
  public get(path: '/dbaas/logs/{serviceName}/input/{inputId}', pathParams: {serviceName: string, inputId: string}): Promise<DbaasLogsInput>;
  /**
  InputConfigtestResult
  Returns the config test operation result
  **/
  public get(path: '/dbaas/logs/{serviceName}/input/{inputId}/configtest/result', pathParams: {serviceName: string, inputId: string}): Promise<DbaasLogsTestResult>;
  /**
  InputAllowedNetworkDetails
  List all network UUID allowed to join input
  **/
  public get(path: '/dbaas/logs/{serviceName}/input/{inputId}/allowedNetwork/{allowedNetworkId}', pathParams: {serviceName: string, inputId: string, allowedNetworkId: string}): Promise<DbaasLogsAllowedNetwork>;
  /**
  InputAllowedNetworks
  List all network UUID allowed to join input
  **/
  public get(path: '/dbaas/logs/{serviceName}/input/{inputId}/allowedNetwork', pathParams: {serviceName: string, inputId: string}): Promise<string[]>;
  /**
  InputUrls
  Returns the list of urls of specified input
  **/
  public get(path: '/dbaas/logs/{serviceName}/input/{inputId}/url', pathParams: {serviceName: string, inputId: string}): Promise<DbaasLogsUrl[]>;
  /**
  InputActions
  Returns actions of specified input
  **/
  public get(path: '/dbaas/logs/{serviceName}/input/{inputId}/action', pathParams: {serviceName: string, inputId: string}): Promise<DbaasLogsInputAction[]>;
  /**
  Inputs
  Returns the list of registered input attached to the logged user
  **/
  public get(path: '/dbaas/logs/{serviceName}/input', pathParams: {serviceName: string}): Promise<string[]>;
  /**
  Service
  Returns the service object of connected identity.
  **/
  public get(path: '/dbaas/logs/{serviceName}', pathParams: {serviceName: string}): Promise<DbaasLogsService>;
  /**
  Service Clusters
  Returns the list of allowed cluster
  **/
  public get(path: '/dbaas/logs/{serviceName}/cluster', pathParams: {serviceName: string}): Promise<string[]>;
  /**
  Service Clusters
  Returns details of an allowed cluster
  **/
  public get(path: '/dbaas/logs/{serviceName}/cluster/{clusterId}', pathParams: {serviceName: string, clusterId: string}): Promise<DbaasLogsCluster>;
  /**
  Cluster allowed networks
  List all the network UUID allowed to contact given cluster
  **/
  public get(path: '/dbaas/logs/{serviceName}/cluster/{clusterId}/allowedNetwork', pathParams: {serviceName: string, clusterId: string}): Promise<string[]>;
  /**
  Cluster allowed networks
  Returns details of an allowed network
  **/
  public get(path: '/dbaas/logs/{serviceName}/cluster/{clusterId}/allowedNetwork/{allowedNetworkId}', pathParams: {serviceName: string, clusterId: string, allowedNetworkId: string}): Promise<DbaasLogsClusterAllowedNetwork>;
  /**
  ServiceOptions
  Returns the subscribed additional options
  **/
  public get(path: '/dbaas/logs/{serviceName}/option', pathParams: {serviceName: string}): Promise<string[]>;
  /**
  ServiceOption
  Returns details of a subscribed option
  **/
  public get(path: '/dbaas/logs/{serviceName}/option/{optionId}', pathParams: {serviceName: string, optionId: string}): Promise<DbaasLogsOption>;
  /**
  Details about a Service
  Get this object properties
  **/
  public get(path: '/dbaas/logs/{serviceName}/serviceInfos', pathParams: {serviceName: string}): Promise<ServicesService>;
  /**
  ServiceOffer
  Returns the subscribed offer
  **/
  public get(path: '/dbaas/logs/{serviceName}/offer', pathParams: {serviceName: string}): Promise<DbaasLogsOffer>;
  /**
  Offer
  Display specified offer
  **/
  public get(path: '/dbaas/logs/offer/{reference}', pathParams: {reference: string}): Promise<DbaasLogsPublicOffer>;
  public get(path: PathsDbaasLogsGET, pathParams?: { [key:string]: string | Number; }, queryParams?: any) : Promise<any> {return super.get(path, pathParams, queryParams);}
  /**
  Role
  Update information of specified role
  **/
  public put(path: '/dbaas/logs/{serviceName}/role/{roleId}', pathParams: {serviceName: string, roleId: string}): Promise<DbaasLogsOperation>;
  /**
  RoleMember
  Update the member metadata
  **/
  public put(path: '/dbaas/logs/{serviceName}/role/{roleId}/member/{username}', pathParams: {serviceName: string, roleId: string, username: string}): Promise<DbaasLogsOperation>;
  /**
  Index
  Update specified elasticsearch index
  **/
  public put(path: '/dbaas/logs/{serviceName}/output/elasticsearch/index/{indexId}', pathParams: {serviceName: string, indexId: string}): Promise<DbaasLogsOperation>;
  /**
  Alias
  Update specified elasticsearch alias
  **/
  public put(path: '/dbaas/logs/{serviceName}/output/elasticsearch/alias/{aliasId}', pathParams: {serviceName: string, aliasId: string}): Promise<DbaasLogsOperation>;
  /**
  Stream
  Update information of specified graylog stream
  **/
  public put(path: '/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}', pathParams: {serviceName: string, streamId: string}): Promise<DbaasLogsOperation>;
  /**
  StreamAlert
  Update alert information of specified graylog stream
  **/
  public put(path: '/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/alert/{alertId}', pathParams: {serviceName: string, streamId: string, alertId: string}): Promise<DbaasLogsOperation>;
  /**
  Dashboard
  Update information of specified graylog dashboard
  **/
  public put(path: '/dbaas/logs/{serviceName}/output/graylog/dashboard/{dashboardId}', pathParams: {serviceName: string, dashboardId: string}): Promise<DbaasLogsOperation>;
  /**
  FlowggerConfiguration
  Update the flowgger configuration
  **/
  public put(path: '/dbaas/logs/{serviceName}/input/{inputId}/configuration/flowgger', pathParams: {serviceName: string, inputId: string}): Promise<DbaasLogsOperation>;
  /**
  LogstashConfiguration
  Update the logstash configuration
  **/
  public put(path: '/dbaas/logs/{serviceName}/input/{inputId}/configuration/logstash', pathParams: {serviceName: string, inputId: string}): Promise<DbaasLogsOperation>;
  /**
  Input
  Update information of specified input object
  **/
  public put(path: '/dbaas/logs/{serviceName}/input/{inputId}', pathParams: {serviceName: string, inputId: string}): Promise<DbaasLogsOperation>;
  /**
  Service
  Update the service properties
  **/
  public put(path: '/dbaas/logs/{serviceName}', pathParams: {serviceName: string}): Promise<DbaasLogsOperation>;
  /**
  Details about a Service
  Alter this object properties
  **/
  public put(path: '/dbaas/logs/{serviceName}/serviceInfos', pathParams: {serviceName: string}): Promise<void>;
  public put(path: PathsDbaasLogsPUT, pathParams?: { [key:string]: string | Number; }, bodyParams?: any) : Promise<any> {return super.put(path, pathParams, bodyParams);}
  /**
  Tokens
  Add a new token
  **/
  public post(path: '/dbaas/logs/{serviceName}/token', pathParams: {serviceName: string}): Promise<DbaasLogsOperation>;
  /**
  ServiceChangePassword
  Initiate a password change procedure.
  **/
  public post(path: '/dbaas/logs/{serviceName}/user/changePassword', pathParams: {serviceName: string}): Promise<DbaasLogsOperation>;
  /**
  Roles
  Register a new role
  **/
  public post(path: '/dbaas/logs/{serviceName}/role', pathParams: {serviceName: string}): Promise<DbaasLogsOperation>;
  /**
  RoleMembers
  Append user into the member list of specified role
  **/
  public post(path: '/dbaas/logs/{serviceName}/role/{roleId}/member', pathParams: {serviceName: string, roleId: string}): Promise<DbaasLogsOperation>;
  /**
  RolePermissionAlias
  Append a elasticsearch alias permission to role
  **/
  public post(path: '/dbaas/logs/{serviceName}/role/{roleId}/permission/alias', pathParams: {serviceName: string, roleId: string}): Promise<DbaasLogsOperation>;
  /**
  RolePermissionIndex
  Append a graylog stream permission to role
  **/
  public post(path: '/dbaas/logs/{serviceName}/role/{roleId}/permission/stream', pathParams: {serviceName: string, roleId: string}): Promise<DbaasLogsOperation>;
  /**
  RolePermissionIndex
  Append a elasticsearch index permission to role
  **/
  public post(path: '/dbaas/logs/{serviceName}/role/{roleId}/permission/index', pathParams: {serviceName: string, roleId: string}): Promise<DbaasLogsOperation>;
  /**
  RolePermissionIndex
  Append a graylog dashboard permission to role
  **/
  public post(path: '/dbaas/logs/{serviceName}/role/{roleId}/permission/dashboard', pathParams: {serviceName: string, roleId: string}): Promise<DbaasLogsOperation>;
  /**
  Indexes
  Register a new elasticsearch index
  **/
  public post(path: '/dbaas/logs/{serviceName}/output/elasticsearch/index', pathParams: {serviceName: string}): Promise<DbaasLogsOperation>;
  /**
  Aliases
  Register a new elasticsearch alias
  **/
  public post(path: '/dbaas/logs/{serviceName}/output/elasticsearch/alias', pathParams: {serviceName: string}): Promise<DbaasLogsOperation>;
  /**
  AliasStreams
  Attach a graylog stream to specified elasticsearch alias
  **/
  public post(path: '/dbaas/logs/{serviceName}/output/elasticsearch/alias/{aliasId}/stream', pathParams: {serviceName: string, aliasId: string}): Promise<DbaasLogsOperation>;
  /**
  AliasStreams
  Attach a elasticsearch index to specified elasticsearch alias
  **/
  public post(path: '/dbaas/logs/{serviceName}/output/elasticsearch/alias/{aliasId}/index', pathParams: {serviceName: string, aliasId: string}): Promise<DbaasLogsOperation>;
  /**
  Streams
  Get a public temporary URL to access the archive
  **/
  public post(path: '/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/archive/{archiveId}/url', pathParams: {serviceName: string, streamId: string, archiveId: string}): Promise<DbaasLogsArchiveUrl>;
  /**
  StreamRules
  Register a new rule on specified graylog stream
  **/
  public post(path: '/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/rule', pathParams: {serviceName: string, streamId: string}): Promise<DbaasLogsOperation>;
  /**
  StreamAlerts
  Register a new alert on specified graylog stream
  **/
  public post(path: '/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/alert', pathParams: {serviceName: string, streamId: string}): Promise<DbaasLogsOperation>;
  /**
  Streams
  Register a new graylog stream
  **/
  public post(path: '/dbaas/logs/{serviceName}/output/graylog/stream', pathParams: {serviceName: string}): Promise<DbaasLogsOperation>;
  /**
  Dashboards
  Register a new graylog dashboard
  **/
  public post(path: '/dbaas/logs/{serviceName}/output/graylog/dashboard', pathParams: {serviceName: string}): Promise<DbaasLogsOperation>;
  /**
  DashboardClone
  Copy all widgets from specified dashboard to a new one
  **/
  public post(path: '/dbaas/logs/{serviceName}/output/graylog/dashboard/{dashboardId}/duplicate', pathParams: {serviceName: string, dashboardId: string}): Promise<DbaasLogsOperation>;
  /**
  InputConfigtest
  Validate configuration of specified input
  **/
  public post(path: '/dbaas/logs/{serviceName}/input/{inputId}/configtest', pathParams: {serviceName: string, inputId: string}): Promise<DbaasLogsOperation>;
  /**
  InputStart
  Schedule the start of specified input
  **/
  public post(path: '/dbaas/logs/{serviceName}/input/{inputId}/start', pathParams: {serviceName: string, inputId: string}): Promise<DbaasLogsOperation>;
  /**
  InputAllowedNetworks
  Allow an ip to join input
  **/
  public post(path: '/dbaas/logs/{serviceName}/input/{inputId}/allowedNetwork', pathParams: {serviceName: string, inputId: string}): Promise<DbaasLogsOperation>;
  /**
  InputEnd
  Schedule the end of specified input
  **/
  public post(path: '/dbaas/logs/{serviceName}/input/{inputId}/end', pathParams: {serviceName: string, inputId: string}): Promise<DbaasLogsOperation>;
  /**
  InputRestart
  Schedule the restart of specified input
  **/
  public post(path: '/dbaas/logs/{serviceName}/input/{inputId}/restart', pathParams: {serviceName: string, inputId: string}): Promise<DbaasLogsOperation>;
  /**
  InputLogs
  Generate a temporary url to retrieve input logs
  **/
  public post(path: '/dbaas/logs/{serviceName}/input/{inputId}/logs/url', pathParams: {serviceName: string, inputId: string}): Promise<DbaasLogsTemporaryLogsLink>;
  /**
  Inputs
  Register a new input object
  **/
  public post(path: '/dbaas/logs/{serviceName}/input', pathParams: {serviceName: string}): Promise<DbaasLogsOperation>;
  /**
  Change the contacts of this service
  Launch a contact change procedure
  **/
  public post(path: '/dbaas/logs/{serviceName}/changeContact', pathParams: {serviceName: string}): Promise<Number[]>;
  /**
  Cluster allowed networks
  Allow an IP to contact cluster
  **/
  public post(path: '/dbaas/logs/{serviceName}/cluster/{clusterId}/allowedNetwork', pathParams: {serviceName: string, clusterId: string}): Promise<DbaasLogsOperation>;
  /**
  ServiceOption
  Remove the specified subscribed option
  **/
  public post(path: '/dbaas/logs/{serviceName}/option/{optionId}/terminate', pathParams: {serviceName: string, optionId: string}): Promise<DbaasLogsOperation>;
  public post(path: PathsDbaasLogsPOST, pathParams?: { [key:string]: string | Number; }, bodyParams?: any) : Promise<any> {return super.post(path, pathParams, bodyParams);}
  /**
  Token
  Delete the specified token
  **/
  public delete(path: '/dbaas/logs/{serviceName}/token/{tokenId}', pathParams: {serviceName: string, tokenId: string}): Promise<DbaasLogsOperation>;
  /**
  Role
  Remove specified role
  **/
  public delete(path: '/dbaas/logs/{serviceName}/role/{roleId}', pathParams: {serviceName: string, roleId: string}): Promise<DbaasLogsOperation>;
  /**
  RoleMember
  Remove user from the member list of specified role
  **/
  public delete(path: '/dbaas/logs/{serviceName}/role/{roleId}/member/{username}', pathParams: {serviceName: string, roleId: string, username: string}): Promise<DbaasLogsOperation>;
  /**
  RolePermission
  Remove specified permission
  **/
  public delete(path: '/dbaas/logs/{serviceName}/role/{roleId}/permission/{permissionId}', pathParams: {serviceName: string, roleId: string, permissionId: string}): Promise<DbaasLogsOperation>;
  /**
  Index
  Remove specified elasticsearch index
  **/
  public delete(path: '/dbaas/logs/{serviceName}/output/elasticsearch/index/{indexId}', pathParams: {serviceName: string, indexId: string}): Promise<DbaasLogsOperation>;
  /**
  Alias
  Remove specified elasticsearch alias
  **/
  public delete(path: '/dbaas/logs/{serviceName}/output/elasticsearch/alias/{aliasId}', pathParams: {serviceName: string, aliasId: string}): Promise<DbaasLogsOperation>;
  /**
  AliasStream
  Detach a graylog stream from specified elasticsearch alias
  **/
  public delete(path: '/dbaas/logs/{serviceName}/output/elasticsearch/alias/{aliasId}/stream/{streamId}', pathParams: {serviceName: string, aliasId: string, streamId: string}): Promise<DbaasLogsOperation>;
  /**
  AliasStream
  Detach a elasticsearch index from specified elasticsearch alias
  **/
  public delete(path: '/dbaas/logs/{serviceName}/output/elasticsearch/alias/{aliasId}/index/{indexId}', pathParams: {serviceName: string, aliasId: string, indexId: string}): Promise<DbaasLogsOperation>;
  /**
  Stream
  Remove specified graylog stream
  **/
  public delete(path: '/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}', pathParams: {serviceName: string, streamId: string}): Promise<DbaasLogsOperation>;
  /**
  StreamRule
  Remove specified graylog stream rule
  **/
  public delete(path: '/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/rule/{ruleId}', pathParams: {serviceName: string, streamId: string, ruleId: string}): Promise<DbaasLogsOperation>;
  /**
  StreamAlert
  Remove alert from specified graylog stream
  **/
  public delete(path: '/dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/alert/{alertId}', pathParams: {serviceName: string, streamId: string, alertId: string}): Promise<DbaasLogsOperation>;
  /**
  Dashboard
  Remove specified graylog dashboard
  **/
  public delete(path: '/dbaas/logs/{serviceName}/output/graylog/dashboard/{dashboardId}', pathParams: {serviceName: string, dashboardId: string}): Promise<DbaasLogsOperation>;
  /**
  Input
  Remove the specified input object
  **/
  public delete(path: '/dbaas/logs/{serviceName}/input/{inputId}', pathParams: {serviceName: string, inputId: string}): Promise<DbaasLogsOperation>;
  /**
  InputAllowedNetworkDetails
  Remove the specified IP from the list of allowed networks
  **/
  public delete(path: '/dbaas/logs/{serviceName}/input/{inputId}/allowedNetwork/{allowedNetworkId}', pathParams: {serviceName: string, inputId: string, allowedNetworkId: string}): Promise<DbaasLogsOperation>;
  /**
  Cluster allowed networks
  Remove the specified IP from the list of allowed networks
  **/
  public delete(path: '/dbaas/logs/{serviceName}/cluster/{clusterId}/allowedNetwork/{allowedNetworkId}', pathParams: {serviceName: string, clusterId: string, allowedNetworkId: string}): Promise<DbaasLogsOperation>;
  public delete(path: PathsDbaasLogsDELETE, pathParams?: { [key:string]: string | Number; }, bodyParams?: any) : Promise<any> {return super.delete(path, pathParams, bodyParams);}
}
