import type { CacheAction, ICacheOptions, OvhRequestable } from '@ovh-api/common';

/**
 * START API /support Models
 * Source: https://ca.api.kimsufi.com/1.0/support.json
 */
export namespace support {
    /**
     * Support ticket message
     * interface fullName: support.Message.Message
     */
    export interface Message {
        body: string;
        creationDate: string;
        from: support.MessageSenderEnum;
        messageId: number;
        ticketId: number;
        updateDate: string;
    }
    /**
     * Message sender type
     * type fullname: support.MessageSenderEnum
     */
    export type MessageSenderEnum = "customer" | "support"
    /**
     * Newly created support identifiers
     * interface fullName: support.NewMessageInfo.NewMessageInfo
     */
    export interface NewMessageInfo {
        additionalNotice?: string;
        messageId: number;
        ticketId: number;
        ticketNumber: number;
    }
    /**
     * Support Ticket
     * interface fullName: support.Ticket.Ticket
     */
    export interface Ticket {
        accountId: string;
        canBeClosed: boolean;
        category?: support.TicketCategoryEnum;
        creationDate: string;
        lastMessageFrom: support.MessageSenderEnum;
        product?: support.TicketProductEnum;
        score: string;
        serviceName?: string;
        state: support.TicketStatusEnum;
        subject: string;
        ticketId: number;
        ticketNumber: number;
        type: support.TicketTypeEnum;
        updateDate: string;
    }
    /**
     * Ticket request category
     * type fullname: support.TicketCategoryEnum
     */
    export type TicketCategoryEnum = "assistance" | "billing" | "incident"
    /**
     * Ticket level of impact or urgency (reserved for Business or Enterprise support level accounts)
     * type fullname: support.TicketImpactUrgencyEnum
     */
    export type TicketImpactUrgencyEnum = "high" | "low" | "medium"
    /**
     * Ticket product
     * type fullname: support.TicketProductEnum
     */
    export type TicketProductEnum = "adsl" | "cdn" | "dedicated" | "dedicated-billing" | "dedicated-other" | "dedicatedcloud" | "domain" | "exchange" | "fax" | "hosting" | "housing" | "iaas" | "mail" | "network" | "publiccloud" | "sms" | "ssl" | "storage" | "telecom-billing" | "telecom-other" | "vac" | "voip" | "vps" | "web-billing" | "web-other"
    /**
     * Support ticket statuses
     * type fullname: support.TicketStatusEnum
     */
    export type TicketStatusEnum = "closed" | "open" | "unknown"
    /**
     * Ticket request subcategory
     * type fullname: support.TicketSubCategoryEnum
     */
    export type TicketSubCategoryEnum = "alerts" | "autorenew" | "bill" | "down" | "inProgress" | "new" | "other" | "perfs" | "start" | "usage"
    /**
     * DEPRECATED - Ticket type (criticalIntervention requires VIP support level)
     * type fullname: support.TicketTypeEnum
     */
    export type TicketTypeEnum = "criticalIntervention" | "genericRequest"
}
/**
 * Api model for /support
 */
export interface Support {
    tickets: {
        /**
         * List support tickets identifiers for this service
         * GET /support/tickets
         */
        $get(params?: { archived?: boolean, category?: support.TicketCategoryEnum, customerReplyNeeded?: boolean, excludeAutogenerated?: boolean, maxCreationDate?: string, minCreationDate?: string, page?: number, pageSize?: number, product?: support.TicketProductEnum, serviceName?: string, status?: support.TicketStatusEnum, subject?: string, ticketNumber?: string }): Promise<number[]>;
        /**
         * Controle cache
         */
        $cache(param?: ICacheOptions | CacheAction): void;
        create: {
            /**
             * Create a new ticket
             * POST /support/tickets/create
             */
            $post(params: { body: string, category?: support.TicketCategoryEnum, impact?: support.TicketImpactUrgencyEnum, product?: support.TicketProductEnum, serviceName?: string, subcategory?: support.TicketSubCategoryEnum, subject: string, type?: support.TicketTypeEnum, urgency?: support.TicketImpactUrgencyEnum, watchers?: string[] }): Promise<support.NewMessageInfo>;
        }
        $(ticketId: number): {
            /**
             * Get ticket
             * GET /support/tickets/{ticketId}
             */
            $get(): Promise<support.Ticket>;
            /**
             * Controle cache
             */
            $cache(param?: ICacheOptions | CacheAction): void;
            canBeScored: {
                /**
                 * Checks whether ticket can be scored
                 * GET /support/tickets/{ticketId}/canBeScored
                 */
                $get(): Promise<boolean>;
                /**
                 * Controle cache
                 */
                $cache(param?: ICacheOptions | CacheAction): void;
            }
            close: {
                /**
                 * Close ticket
                 * POST /support/tickets/{ticketId}/close
                 */
                $post(): Promise<void>;
            }
            messages: {
                /**
                 * Get ticket messages
                 * GET /support/tickets/{ticketId}/messages
                 */
                $get(): Promise<support.Message[]>;
                /**
                 * Controle cache
                 */
                $cache(param?: ICacheOptions | CacheAction): void;
            }
            reopen: {
                /**
                 * Reopen a ticket
                 * POST /support/tickets/{ticketId}/reopen
                 */
                $post(params: { body: string }): Promise<void>;
            }
            reply: {
                /**
                 * Reply to ticket
                 * POST /support/tickets/{ticketId}/reply
                 */
                $post(params: { body: string }): Promise<void>;
            }
            score: {
                /**
                 * Set ticket score
                 * POST /support/tickets/{ticketId}/score
                 */
                $post(params: { score: string, scoreComment?: string }): Promise<void>;
            }
        };
    }
}

export declare function proxySupport(ovhEngine: OvhRequestable): Support;
export default proxySupport;
